apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
  - namespace.yaml
labels:
  - pairs:
      app: mealie
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.11.1
    releaseName: longhorn
    namespace: longhorn
    valuesFile: values-longhorn.yaml

