apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
  - namespace.yaml

labels:
  - pairs:
      app: mealie

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.28.0
    releaseName: postgres
    namespace: database
    valuesFile: values-postgres.yaml
