apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - namespace.yaml
  - secret.yaml

commonLabels:
  app: mealie

helmCharts:
  - name: postgres
    repo: https://charts.fossa.com
    version: 2.0.0
    releaseName: postgres
    namespace: database
    valuesFile: values-postgres.yaml
