
postgresqlUsername: mealie
postgresqlPassword: mealie
postgresqlDatabase: mealie
 
service:
  type: ClusterIP
  port: 5432
 
persistence:
  enabled: true
  size: 3Gi
  # storageClass: ""  # uncomment and set if needed
 
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
 
imageTag: "15"
