database: fossa
username: fossa
password: fossa123
image.registry: quay.io
image.repository: fossa/postgres
image.tag: 17.2-1

imageCredentials:
	username: fossa+customer
	password: HELLOWORLD1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
