replicaCount: 1

image:
  repository: testingkyaw/mealie
  tag: v2
  pullPolicy: IfNotPresent

containerPort: 9000


db:
  host: mealie-db-postgresql.database.svc.cluster.local
  port: "5432"

service:
  type: NodePort
  port: 9000
  nodePort: 30900

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
